const categories = [
  {
    slug: "haircut",
    id: 1,
    pathdark: "/assets/dark-catogories-avatar.svg",
    pathlight: "/assets/dark-catogories.svg",
    active: true,
    bannerMeta: {
      title: "Haircut",
      subtitle: "Get a fresh new look with our expert haircut services.",
      imageSrc: "/assets/haircut.jpg",
      caption: "Transform your hairstyle today!",
      backgroundColor: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
    },
    services: [
      {
        id: 1,
        label: "Shoulder Length Hair Cut",
        desc: "This is a description that talks about the details of the service.",
        time: 45,
        ratings: 4,
        reviews: 198,
        prize: 500,
      },
      {
        id: 2,
        label: "Layered Haircut",
        desc: "This is a description that talks about the details of the service.",
        time: 45,
        ratings: 4,
        reviews: 198,
        prize: 500,
      },
      {
        id: 3,
        label: "Hair Styling",
        desc: "This is a description that talks about the details of the service.",
        time: 45,
        ratings: 4,
        reviews: 198,
        prize: 500,
      },
    ],
  },
  {
    slug: "facial",
    id: 2,
    pathdark: "/assets/dark-catogories-avatar.svg",
    active: false,
    label: "Facial",
    bannerdesc: "Get glowing skin!",
    offerDesc: "Earn 5 care coins on each appointment",
    bannerimg: "/assets/makeup.svg",
    pathlight: "/assets/light-catogories-avatar.svg",
    services: [
      {
        id: 1,
        label: "Basic Facial",
        desc: "This is a description that talks about the details of the service.",
        time: 60,
        ratings: 4.5,
        reviews: 220,
        prize: 800,
      },
    ],
  },
  {
    slug: "Nails",
    id: 3,
    pathdark: "/assets/dark-catogories-avatar.svg",
    active: false,
    bannerimg: "/assets/others.svg",
    bannerdesc: "Get a glowing skin!",
    offerDesc: "Earn 5 care coins on each appointment",
    label: "Nails",
    pathlight: "/assets/light-catogories-avatar.svg",
    services: [
      {
        id: 1,
        label: "Manicure",
        desc: "This is a description that talks about the details of the service.",
        time: 30,
        ratings: 4.2,
        reviews: 150,
        prize: 400,
      },
    ],
  },
  {
    slug: "others",
    id: 5,
    pathdark: "/assets/dark-catogories-avatar.svg",
    active: false,
    bannerimg: "/assets/others.svg",
    bannerdesc: "Get a glowing skin!",
    offerDesc: "Earn 5 care coins on each appointment",
    label: "Others",
    pathlight: "/assets/light-catogories-avatar.svg",
    services: [],
  },
];
